---
- hosts: client
  become: yes

  vars:
    username: klientas	
    password: topkek
    

  tasks:

  - name: Creating user
    user: 
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512') }}"
      group: root

  - name: Install required software
    apt:
      name={{ item }} update_cache=yes state=latest
    with_items:
      - ufw

  - name: restart ufw
    service: name=ufw state=restarted