---
- hosts: web
  become: yes

  vars:
    http_port: 80
    mysql_db: webas	
    mysql_user: topkekas
    mysql_password: topkekaspass
    mysql_host: "{{lookup('file', '/etc/ansible/mysql.txt') }}"

  tasks:

  - name: install required software
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
        - apache2
        - php7.0-mysql
        - php7.0
        - libapache2-mod-php
        - php7.0-mcrypt
        - python-mysqldb
        - mysql-client
        - git
 
  - name: delete apache index
    command: rm /var/www/html/index.html 

  - git:
      repo: 'https://github.com/RokasAlechnavicius/virtualwebaskopija.git'
      dest: /var/www/html
      update: no

  - name: Update PHP config file
    command: sed -i 's/10.0.0.222/{{ mysql_host }}/g' /var/www/html/config.php
    notify:
    - restart apache

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
