---
- hosts: web
  sudo: yes
  sudo_user: root
  remote_user: root

  vars:
    http_port: 80
    mysql_db: webas	
    mysql_user: topkekas
    mysql_password: topkekaspass
    mysql_host: "{{lookup('file', '/etc/ansible/db.txt') }}"

  tasks:

  - name: install required software
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
        - apache2
        - php7.0-mysql
        - php7.0
        - libapache2-mod-php
        - php7.0-mcrypt
        - python-mysqldb
        - mysql-client
        - git
 
 
  - git:
      repo: 'https://github.com/RokasAlechnavicius/virtualwebaskopija.git'
      dest: /var/www/html

  - name: Update PHP config file
    command: sudo sed -i 's/10.0.1.222/{{ mysql_host }}/g' var/www/html
    notify:
    - restart apache

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted